language: python
dist: trusty
sudo: true

jobs:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

install:
  - pip install pyinstaller

script:
  - ./eac_logchecker.py logs/01.log